# docker run --network=my-network -p 4000:4000 \\
# -e REACT_APP_PROFILE_API_HOST=http://profile-management \\
# -e REACT_APP_PRODUCT_API_HOST=http://product-catalog \\
# -e REACT_APP_INVENTORY_API_HOST=http://product-inventory \\
# -e REACT_APP_ORDER_API_HOST=http://order-management \\
# -e REACT_APP_SHIPPING_API_HOST=http://shipping-and-handling \\
# -e REACT_APP_CONTACT_API_HOST=http://contact-support-team \\
# --name ecommerce-ui rslim087/ecommerce-ui

# docker run -p 8080:8080 -e MONGO_URI=<mongo_uri> shipping-and-handling

# docker run -p 3003:3003 -e MYSQL_HOST=<mysql_host> -e MYSQL_PORT=<mysql_port> -e MYSQL_USER=<mysql_user> -e MYSQL_PASSWORD=<mysql_password> -e MYSQL_DATABASE=<mysql_database> authentication-microservice

# docker run -p 3002:3002 -e POSTGRES_HOST=<postgres_host> -e POSTGRES_PORT=<postgres_port> -e POSTGRES_DB=<postgres_db> -e POSTGRES_USER=<postgres_user> -e POSTGRES_PASSWORD=<postgres_password> product-inventory-microservice

# docker run -p 8000:8000 -e MONGODB_HOST=<mongo_host> -e MONGODB_PORT=<mongo_port> -e MONGODB_DATABASE=<mongo_database> contact-support-microservice

# docker run -p 3001:3001 -e MONGODB_HOST=<mongo_host> -e MONGODB_PORT=<mongo_port> -e MONGODB_DATABASE=<mongo_database> product-catalog-microservice

# docker run --network my-network \
#   -e PRODUCT_INVENTORY_API_HOST=http://product-inventory \
#   -e PRODUCT_CATALOG_API_HOST=http://product-catalog \
#   -e SHIPPING_HANDLING_API_HOST=http://shipping-and-handling \
#   -e SPRING_DATA_MONGODB_URI=mongodb://host:27017/name \
#   -e SPRING_DATA_MONGODB_DATABASE=order_management \
#   -p 9090:9090 --name order-management rslim087/order-management

version: "3.8"
services:
  ecommerce-ui:
    image: thuongtt060797/ecommerce-ui:1.0.0
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_PROFILE_API_HOST=http://profile-management
      - REACT_APP_PRODUCT_API_HOST=http://product-catalog
      - REACT_APP_INVENTORY_API_HOST=http://product-inventory
      - REACT_APP_ORDER_API_HOST=http://order-management
      - REACT_APP_SHIPPING_API_HOST=http://shipping-and-handling
      - REACT_APP_CONTACT_API_HOST=http://contact-support-team
    depends_on:
      - profile-management
      - product-catalog
      - product-inventory
      - order-management
      - shipping-and-handling
      - contact-support-team

  shipping-and-handling:
    image: thuongtt060797/shipping-and-handling:1.0.0
    ports:
      - "8080:8080"
    depends_on:
      - mongodb_shipping
    environment:
      - MONGO_URI=mongo://mongodb_shipping:27017

  mongodb_shipping: # Sẽ chạy mặc định trên cổng 27017
    image: mongo
    container_name: mongodb_shipping
    volumes:
      - mongodb_shipping_data:/data/db # /data/db là thư mục chứa dữ liệu của MongoDB trong container

  contact-support-team:
    image: thuongtt060797/contact-support-team:1.0.0
    ports:
      - "8000:8000"
    depends_on:
      - mongodb_contact_support
    environment:
      - MONGODB_HOST=mongodb_contact_support
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=contact_support

  mongodb_contact_support: # Sẽ chạy mặc định trên cổng 27017
    image: mongo
    container_name: mongodb_contact_support
    volumes:
      - mongodb_contact_support_data:/data/db # /data/db là thư mục chứa dữ liệu của MongoDB trong container

  product-catalog:
    image: thuongtt060797/product-catalog:1.0.0
    ports:
      - "3001:3001"
    depends_on:
      - mongodb_product_catalog
    environment:
      - MONGODB_HOST=mongodb_product_catalog
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=product_catalog

  mongodb_product_catalog: # Sẽ chạy mặc định trên cổng 27017
    image: mongo
    container_name: mongodb_product_catalog
    volumes:
      - mongodb_product_catalog_data:/data/db # /data/db là thư mục chứa dữ liệu của MongoDB trong container

  order-management:
    image: thuongtt060797/order-management:1.0.0
    ports:
      - "9090:9090"
    depends_on:
      - mongodb_order_management
    environment:
      - SHIPPING_HANDLING_API_HOST=http://shipping-and-handling
      - PRODUCT_INVENTORY_API_HOST=http://product-inventory
      - PRODUCT_CATALOG_API_HOST=http://product-catalog
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb_order_management:27017/order_management

  mongodb_order_management: # Sẽ chạy mặc định trên cổng 27017
    image: mongo
    container_name: mongodb_order_management
    volumes:
      - mongodb_order_management_data:/data/db # /data/db là thư mục chứa dữ liệu của MongoDB trong container

  product-inventory:
    image: thuongtt060797/product-inventory:1.0.0
    ports:
      - "3002:3002"
    depends_on:
      - postgres_product_inventory
    environment:
      - POSTGRES_HOST=postgres_product_inventory
      - POSTGRES_PORT=5432
      - POSTGRES_DB=product_inventory
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password

  postgres_product_inventory: # Sẽ chạy mặc định trên cổng 5432
    image: postgres:14
    container_name: postgres_product_inventory
    environment:
      - POSTGRES_DB=product_inventory
      - POSTGRES_USER=inventory_user
      - POSTGRES_PASSWORD=inventory_password
    volumes:
      - postgres_product_inventory_data:/var/lib/postgresql/data # Thư mục chứa dữ liệu của PostgreSQL trong container

  profile-management:
    image: thuongtt060797/profile-management:1.0.0
    ports:
      - "3003:3003"
    depends_on:
      - mysql_profile_management
    environment: # Các biến môi trường cần thiết để kết nối với MySQL
      - MYSQL_HOST=mysql_profile_management # Tên của service MySQL
      - MYSQL_PORT=3306 # Cổng mặc định của MySQL
      - MYSQL_DATABASE=profile_management # Tên cơ sở dữ liệu
      - MYSQL_USER=profile_user # Tên người dùng
      - MYSQL_PASSWORD=profile_password # Mật khẩu người dùng

  mysql_profile_management: # Sẽ chạy mặc định trên cổng 3306
    image: mysql:8.0
    container_name: mysql_profile_management
    environment:
      - MYSQL_DATABASE=profile_management # Tên cơ sở dữ liệu
      - MYSQL_USER=profile_user # Tên người dùng
      - MYSQL_PASSWORD=profile_password # Mật khẩu người dùng
      - MYSQL_ROOT_PASSWORD=root_password # Mật khẩu root
    volumes:
      - mysql_profile_management_data:/var/lib/mysql # Thư mục chứa dữ liệu của MySQL trong container
volumes:
  mongodb_product_catalog_data:
  mongodb_contact_support_data:
  mongodb_shipping_data:
  mongodb_order_management_data:
  mysql_profile_management_data:
  postgres_product_inventory_data:
