version: "3.8"
services:
  ecommerce-ui:
    image: thuongtt060797/ecommerce-ui:1.0.0
    ports:
      - "4000:4000"
    environment:
      - REACT_APP_PROFILE_API_HOST=http://profile-management
      - REACT_APP_PRODUCT_API_HOST=http://product-catalog
      - REACT_APP_INVENTORY_API_HOST=http://product-inventory
      - REACT_APP_ORDER_API_HOST=http://order-management
      - REACT_APP_SHIPPING_API_HOST=http://shipping-and-handling
      - REACT_APP_CONTACT_API_HOST=http://contact-support-team
    depends_on:
      - profile-management
      - product-catalog
      - product-inventory
      - order-management
      - shipping-and-handling
      - contact-support-team

  profile-management:
    image: thuongtt060797/profile-management:1.0.0
    ports:
      - "3003:3003"

  shipping-and-handling:
    image: thuongtt060797/shipping-and-handling:1.0.0
    ports:
      - "8080:8080"

  contact-support-team:
    image: thuongtt060797/contact-support-team:1.0.0
    ports:
      - "8000:8000"

  product-inventory:
    image: thuongtt060797/product-inventory:1.0.0
    ports:
      - "3002:3002"

  product-catalog:
    image: thuongtt060797/product-catalog:1.0.0
    ports:
      - "3001:3001"

  order-management:
    image: thuongtt060797/order-management:1.0.0
    ports:
      - "9090:9090"
    environment:
      - SHIPPING_HANDLING_API_HOST=http://shipping-and-handling
      - PRODUCT_INVENTORY_API_HOST=http://product-inventory
      - PRODUCT_CATALOG_API_HOST=http://product-catalog
