version: "3"
services:
  flask-app:
    image: thuongtt060797/grade-submission-portal
    container_name: flask-app
    ports:
      - "5001:5001"
    environment:
      - GRADE_SERVICE_HOST=node-server
    depends_on:
      - node-server

  node-server:
    image: thuongtt060797/grade-submission-api:2.0.0
    container_name: node-server
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_NAME=grade_db
    ports:
      - "3000:3000"
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=grade_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
